# Generated by Django 5.1.5 on 2025-02-14 17:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PN', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 2, 14, 17, 15, 7, 292059, tzinfo=datetime.timezone.utc), verbose_name='Fecha de emision')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aprovador', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
                ('Emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emisor', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
                ('proyecto', models.ManyToManyField(related_name='get_posts', to='core.project', verbose_name='Proyectos')),
            ],
            options={
                'verbose_name': 'Drawing',
                'ordering': ['-created'],
            },
        ),
    ]
