# Generated by Django 5.1.5 on 2025-02-14 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 17, 18, 22, 72253, tzinfo=datetime.timezone.utc), verbose_name='Fecha de emision'),
        ),
    ]
