# Generated by Django 5.1.6 on 2025-02-18 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_drawing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='Revision',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='Status',
            field=models.CharField(default='Ready for review', max_length=100),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 12, 35, 45, 897229, tzinfo=datetime.timezone.utc), verbose_name='Fecha de emision'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='proyecto',
            field=models.ManyToManyField(to='core.project', verbose_name='Proyectos'),
        ),
    ]
