# Generated by Django 5.1.6 on 2025-02-18 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drawing_revision_alter_drawing_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='Aprovador',
            new_name='Aprobador',
        ),
        migrations.AlterField(
            model_name='drawing',
            name='Status',
            field=models.CharField(choices=[('Ready for review', 'Ready for review'), ('Sent for corrections', 'Sent for corrections'), ('Proposal OK', 'Proposal OK'), ('PLM uploaded', 'PLM uploaded')], default='Not started', max_length=100),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 14, 34, 20, 375325, tzinfo=datetime.timezone.utc), verbose_name='Fecha de emision'),
        ),
    ]
